fix: import existing cloudwatch log group

diff --git a/.github/workflows/infra-deploy.yml b/.github/workflows/infra-deploy.yml
--- a/.github/workflows/infra-deploy.yml
+++ b/.github/workflows/infra-deploy.yml
@@ -39,9 +39,9 @@ jobs:
         working-directory: infra/terraform
         run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}"
 
-      - name: Force Unlock Terraform State
+      - name: Import Existing Log Group
         working-directory: infra/terraform
-        run: terraform force-unlock -force f2d4a15c-18f7-36cc-1723-02ba2eb1d634
+        run: terraform import -var="aws_region=${{ secrets.AWS_REGION }}" module.eks.aws_cloudwatch_log_group.this[0] /aws/eks/devsecops-cluster/cluster || echo "Import failed or already imported"
         env:
           AWS_REGION: ${{ secrets.AWS_REGION }}
 
